const products = [
    {
        "priorityshipping_id": "210589",
        "product_type": "682",
        "parent_product_sku": "KC03534",
        "metal_selection": "133265,134045",
        "metal_karat_selection": "14k",
        "diamond_quality": "177641",
        "product_size": "294",
        "chain_thickness": "",
        "gold_metal_weight": "3.79",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "3.82",
        "priority_order": "1",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100028272",
        "order_item_id": "401100028272",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2024-11-08 08:03:32",
        "updated_at": "2025-03-26 12:03:56",
        "design_identifier": "35085P",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100028272",
        "diamond_configurations": "[{\"diamond_weight\":\"0.0088235294117647\",\"diamond_qty\":\"17\",\"record_id\":\"0\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"}]",
        "product_name": "Vadim Gold Chain",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "46061",
        "product_data": {
            "metal": [
                {
                    "id": "134045",
                    "name": "Yellow Gold",
                    "sku": "KC03534",
                    "code": "yellow-gold",
                    "color": "Yellow",
                    "price": 19405,
                    "cost_price": 19405,
                    "purity": "14K",
                    "purityPrice": 5120,
                    "weight": "3.79",
                    "web_percent": "0.583",
                    "cost_percent": "0.583",
                    "product_metal_id": "133265"
                }
            ],
            "material_detail": "Diamond",
            "stone": [
                {
                    "clarity": "SI IJ",
                    "color": "IJ",
                    "no_of_diamonds": "17",
                    "weight": "0.0088235294117647",
                    "shape": "Round",
                    "total_weight": 0.15,
                    "setting_type": "",
                    "price": 17850,
                    "cost_price": 303450,
                    "weight_range": "0.001-0.0749"
                }
            ],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [],
            "sku": "KC03534",
            "making_charge": 9475,
            "making_rate": 2500,
            "price": 94832,
            "discount_applied_price": 112575,
            "discount_label": "20% Off on Stone Price",
            "rating": 5,
            "total_rating":1,
            "cost_price": 334980,
            "margin": 2,
            "metal_price": 19405,
            "stone_price": 17850,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 1402,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 0,
            "total_metal_weight": 3.79,
            "total_stone_weight": 0.15,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0,
            "total_weight": 3.82,
            "total_stone_numbers": 17,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": "43.81 cm",
            "sub_size": "17.25 inch",
            "is_priority_shipping": 1,
            "priorityshipping_id": 210589,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4892912",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05254RG_1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "133265"
                },
                {
                    "id": "4892915",
                    "label": "Front Full View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05254RG_creative.jpeg",
                    "sort_order": "11",
                    "roles": "",
                    "product_metal_id": "133265"
                },
                {
                    "id": "4892918",
                    "label": "Diagonal View-Left",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05254RG_2.jpeg",
                    "sort_order": "12",
                    "roles": "",
                    "product_metal_id": "133265"
                },
                {
                    "id": "4892921",
                    "label": "Dimension Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05254RG_3.jpeg",
                    "sort_order": "13",
                    "roles": "",
                    "product_metal_id": "133265"
                },
                {
                    "id": "4892924",
                    "label": "Front View-Open Lock",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05255RG_creative.jpeg",
                    "sort_order": "14",
                    "roles": "hover",
                    "product_metal_id": "133265"
                },
                {
                    "id": "4892927",
                    "label": "Rendered Model Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05258RG_creative.jpeg",
                    "sort_order": "15",
                    "roles": "",
                    "product_metal_id": "133265"
                }
            ],
            "videos": []
        }
    },
    {
        "priorityshipping_id": "309661",
        "product_type": "586",
        "parent_product_sku": "C019204",
        "metal_selection": "80445,79839",
        "metal_karat_selection": "14k",
        "diamond_quality": "104013",
        "product_size": "111",
        "chain_thickness": "",
        "gold_metal_weight": "6.13",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "6.22",
        "priority_order": "1",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100001668",
        "order_item_id": "401100001668",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2025-01-07 10:14:00",
        "updated_at": "2025-03-26 12:08:41",
        "design_identifier": "LDBA0004PR04",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100001668",
        "diamond_configurations": "[{\"diamond_weight\":\"0.0074137931034483\",\"diamond_qty\":\"58\",\"record_id\":\"0\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"}]",
        "product_name": "Savina Diamond Hoop Earrings",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "29554",
        "product_data": {
            "metal": [
                {
                    "id": "79839",
                    "name": "Rose Gold",
                    "sku": "C019204",
                    "code": "rose-gold",
                    "color": "Rose",
                    "price": 31386,
                    "cost_price": 31386,
                    "purity": "14K",
                    "purityPrice": 5120,
                    "weight": "6.13",
                    "web_percent": "0.583",
                    "cost_percent": "0.583",
                    "product_metal_id": "80445"
                }
            ],
            "material_detail": "Diamond",
            "stone": [
                {
                    "clarity": "SI IJ",
                    "color": "IJ",
                    "no_of_diamonds": "58",
                    "weight": "0.0074137931034483",
                    "shape": "Round",
                    "total_weight": 0.43,
                    "setting_type": "",
                    "price": 51170,
                    "cost_price": 2967860,
                    "weight_range": "0.001-0.0749"
                }
            ],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [],
            "sku": "C019204",
            "making_charge": 15325,
            "making_rate": 2500,
            "price": 159303,
            "discount_applied_price": 180000,
            "discount_label": "20% Off on Stone Price",
            "rating": 5,
            "total_rating":6,
            "cost_price": 3093327,
            "margin": 2,
            "metal_price": 31386,
            "stone_price": 51170,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 2936,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 0,
            "total_metal_weight": 6.13,
            "total_stone_weight": 0.43,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0,
            "total_weight": 6.22,
            "total_stone_numbers": 58,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": "2.4",
            "sub_size": "57.2 mm",
            "is_priority_shipping": 1,
            "priorityshipping_id": 309661,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4443381",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C006361__1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "80445"
                },
                {
                    "id": "4443402",
                    "label": "Dimension Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C006361__5.jpeg",
                    "sort_order": "14",
                    "roles": "",
                    "product_metal_id": "80445"
                },
                {
                    "id": "4443384",
                    "label": "Diagonal View-Right",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C006361__2.jpeg",
                    "sort_order": "11",
                    "roles": "hover",
                    "product_metal_id": "80445"
                },
                {
                    "id": "4443393",
                    "label": "Side View 1",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C006361__3.jpeg",
                    "sort_order": "12",
                    "roles": "",
                    "product_metal_id": "80445"
                },
                {
                    "id": "4443396",
                    "label": "Side View 2",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C006361__4.jpeg",
                    "sort_order": "13",
                    "roles": "",
                    "product_metal_id": "80445"
                },
                
            ],
            "videos": [
                {
                    "id": "86599",
                    "label": "Model Creative Video",
                    "thumbnail": "https://mcstaging.candere.com/media/jewellery/images/Candere-Logo_124.jpg",
                    "video": "https://mcstaging.candere.com/media/jewellery/videos/C019204_Model_Video_2.mp4",
                    "sort_order": "101",
                    "product_metal_id": "80445"
                }
            ]
        }
    },
    {
        "priorityshipping_id": "193183",
        "product_type": "584",
        "parent_product_sku": "C015270",
        "metal_selection": "47445,47592",
        "metal_karat_selection": "14k",
        "diamond_quality": "66684",
        "product_size": "",
        "chain_thickness": "",
        "gold_metal_weight": "1.42",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "1.43",
        "priority_order": "2",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100035876",
        "order_item_id": "401100035876",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2024-10-28 06:25:06",
        "updated_at": "2025-03-26 12:19:44",
        "design_identifier": "cner1744",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100035876",
        "diamond_configurations": "[{\"diamond_weight\":\"0.015\",\"diamond_qty\":\"2\",\"record_id\":\"0\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"}]",
        "product_name": "Starlight Diamond Eternity Rings",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "9455",
        "product_data": {
            "metal": [
                {
                    "id": "47592",
                    "name": "Yellow Gold",
                    "sku": "C015270",
                    "code": "yellow-gold",
                    "color": "Yellow",
                    "price": 7270,
                    "cost_price": 7270,
                    "purity": "14K",
                    "purityPrice": 5120,
                    "weight": "1.42",
                    "web_percent": "0.583",
                    "cost_percent": "0.583",
                    "product_metal_id": "47445"
                }
            ],
            "material_detail": "Diamond",
            "stone": [
                {
                    "clarity": "SI GH",
                    "color": "GH",
                    "no_of_diamonds": "2",
                    "weight": "0.015",
                    "shape": "Round",
                    "total_weight": 0.03,
                    "setting_type": "",
                    "price": 4110,
                    "cost_price": 8220,
                    "weight_range": "0.001-0.0749"
                }
            ],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [],
            "sku": "C015270",
            "making_charge": 4178,
            "making_rate": 2942,
            "price": 39303,
            "discount_applied_price": 45000,
            "discount_label": "20% Off on Stone Price",
            "rating": 5,
            "total_rating":6,
            "cost_price": 17963,
            "margin": 2,
            "metal_price": 7270,
            "stone_price": 4110,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 467,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 0,
            "total_metal_weight": 1.42,
            "total_stone_weight": 0.03,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0,
            "total_weight": 1.43,
            "total_stone_numbers": 2,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": null,
            "sub_size": "",
            "is_priority_shipping": 1,
            "priorityshipping_id": 193183,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4313805",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/catalog/product/C/0/C000149__1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "47445"
                },
                {
                    "id": "4313808",
                    "label": "Diagonal View-Left",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C000149__5.jpeg",
                    "sort_order": "11",
                    "roles": "hover",
                    "product_metal_id": "47445"
                },
                {
                    "id": "4313811",
                    "label": "Side View 1",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C000149__2.jpeg",
                    "sort_order": "12",
                    "roles": "",
                    "product_metal_id": "47445"
                },
                {
                    "id": "4313814",
                    "label": "Dimension Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C000149__3.jpeg",
                    "sort_order": "13",
                    "roles": "",
                    "product_metal_id": "47445"
                },
                {
                    "id": "4313817",
                    "label": "Rendered Model Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C000149__4.jpeg",
                    "sort_order": "14",
                    "roles": "",
                    "product_metal_id": "47445"
                }
            ],
            "videos": []
        }
    },
    {
        "priorityshipping_id": "191905",
        "product_type": "584",
        "parent_product_sku": "KC04211",
        "metal_selection": "135179,135959",
        "metal_karat_selection": "14k",
        "diamond_quality": "178940",
        "product_size": "",
        "chain_thickness": "",
        "gold_metal_weight": "1.12",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "1.43",
        "priority_order": "1",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100022596",
        "order_item_id": "401100022596",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2024-10-28 06:20:47",
        "updated_at": "2025-03-26 12:17:41",
        "design_identifier": "ER-10216",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100022596",
        "diamond_configurations": "[{\"diamond_weight\":\"0.02\",\"diamond_qty\":\"2\",\"record_id\":\"0\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"}]",
        "product_name": "Taniya Diamond Necklace",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "46712",
        "product_data": {
            "metal": [
                {
                    "id": "135959",
                    "name": "Rose Gold",
                    "sku": "KC04211",
                    "code": "rose-gold",
                    "color": "Rose",
                    "price": 5734,
                    "cost_price": 5734,
                    "purity": "14K",
                    "purityPrice": 5120,
                    "weight": "1.12",
                    "web_percent": "0.583",
                    "cost_percent": "0.583",
                    "product_metal_id": "135179"
                }
            ],
            "material_detail": "Diamond",
            "stone": [
                {
                    "clarity": "SI GH",
                    "color": "GH",
                    "no_of_diamonds": "2",
                    "weight": "0.02",
                    "shape": "Round",
                    "total_weight": 0.04,
                    "setting_type": "",
                    "price": 5480,
                    "cost_price": 10960,
                    "weight_range": "0.001-0.0749"
                }
            ],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [
                {
                    "weight": 0.35,
                    "price": 0,
                    "old_price": 0,
                    "code": "Silicone",
                    "label": "Silicone wt. ",
                    "is_price_enabled": "0",
                    "is_price_type": "0"
                }
            ],
            "sku": "KC04211",
            "making_charge": 2317,
            "making_rate": 2069,
            "price": 76347,
            "discount_applied_price": 80000,
            "discount_label": "20% Off on Stone Price",
            "rating": 4.8,
            "total_rating":8,
            "cost_price": 17945,
            "margin": 2,
            "metal_price": 5734,
            "stone_price": 5480,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 406,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 14634,
            "total_metal_weight": 1.12,
            "total_stone_weight": 0.04,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0.35,
            "total_weight": 1.48,
            "total_stone_numbers": 2,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": null,
            "sub_size": "",
            "is_priority_shipping": 1,
            "priorityshipping_id": 191905,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4864298",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05408YG_1_1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "135179"
                },
                {
                    "id": "4864301",
                    "label": "Diagonal View-Left",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05408YG_6.jpeg",
                    "sort_order": "11",
                    "roles": "hover",
                    "product_metal_id": "135179"
                },
                {
                    "id": "4864304",
                    "label": "Side View 1",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05408YG_5.jpeg",
                    "sort_order": "12",
                    "roles": "",
                    "product_metal_id": "135179"
                },
                {
                    "id": "4864307",
                    "label": "Dimension Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05408YG_2.jpeg",
                    "sort_order": "13",
                    "roles": "",
                    "product_metal_id": "135179"
                },
                {
                    "id": "4864310",
                    "label": "Rendered Model Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC05408YG_4.jpeg",
                    "sort_order": "14",
                    "roles": "",
                    "product_metal_id": "135179"
                },
            ],
        }
    },
    {
        "priorityshipping_id": "210340",
        "product_type": "682",
        "parent_product_sku": "NK00186",
        "metal_selection": "103438,103345",
        "metal_karat_selection": "18k",
        "diamond_quality": "",
        "product_size": "294",
        "chain_thickness": "",
        "gold_metal_weight": "3.97",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "3.97",
        "priority_order": "1",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100023747",
        "order_item_id": "401100023747",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2024-11-08 08:03:27",
        "updated_at": "2025-03-26 12:03:46",
        "design_identifier": "cnnk592",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100023747",
        "diamond_configurations": "[]",
        "product_name": "Taram Gold Jhumki",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "34224",
        "product_data": {
            "metal": [
                {
                    "id": "103345",
                    "name": "Yellow Gold",
                    "sku": "NK00186",
                    "code": "yellow-gold",
                    "color": "Yellow",
                    "price": 26150,
                    "cost_price": 26150,
                    "purity": "18K",
                    "purityPrice": 6587,
                    "weight": "3.97",
                    "web_percent": "0.75",
                    "cost_percent": "0.75",
                    "product_metal_id": "103438"
                }
            ],
            "material_detail": "Gold",
            "stone": [],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [],
            "sku": "NK00186",
            "making_charge": 11116,
            "making_rate": 2800,
            "price": 38123,
            "discount_applied_price": 43639,
            "discount_label": "20% Off on Stone Price",
            "rating": 5,
            "total_rating":1,
            "cost_price": 29184,
            "margin": 24,
            "metal_price": 26150,
            "stone_price": 0,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 1118,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 0,
            "total_metal_weight": 3.97,
            "total_stone_weight": 0,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0,
            "total_weight": 3.97,
            "total_stone_numbers": 0,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": "43.81 cm",
            "sub_size": "17.25 inch",
            "is_priority_shipping": 1,
            "priorityshipping_id": 210340,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4490015",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/jewellery/images/GE00469_1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "103438"
                },
                {
                    "id": "4490018",
                    "label": "Front Full View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/GE00469_Hand_creative.jpeg",
                    "sort_order": "11",
                    "roles": "",
                    "product_metal_id": "103438"
                },
                {
                    "id": "4490021",
                    "label": "Diagonal View-Left",
                    "metal_image": "https://www.candere.com/media/jewellery/images/GE00469_2.jpeg",
                    "sort_order": "12",
                    "roles": "hover",
                    "product_metal_id": "103438"
                },
                {
                    "id": "4490024",
                    "label": "Top Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/GE00469_2.jpeg",
                    "sort_order": "13",
                    "roles": "",
                    "product_metal_id": "103438"
                },
                {
                    "id": "4490027",
                    "label": "Rendered Model Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/GE00469_Hand_creative.jpeg",
                    "sort_order": "15",
                    "roles": "",
                    "product_metal_id": "103438"
                }
            ],
            "videos": [],
            "discount_making_charge": 6114,
            "discount_applied_price": 33232,
            "discount_label": "20% Off on Stone Price",
            "discount_gst": 968,
            "discount_price_type": "Making Charges",
            "discount_code": "SPLASH",
            "discount_label": "45% OFF on Making",
            "you_saved": 5151.98
        }
    },
    {
        "priorityshipping_id": "302500",
        "product_type": "1057",
        "parent_product_sku": "C015406",
        "metal_selection": "51216,51429",
        "metal_karat_selection": "14k",
        "diamond_quality": "70989",
        "product_size": "219",
        "chain_thickness": "",
        "gold_metal_weight": "2.45",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "3.69",
        "priority_order": "1",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100014839",
        "order_item_id": "401100014839",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2025-01-07 10:08:33",
        "updated_at": "2025-03-26 12:25:12",
        "design_identifier": "cntm326",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100014839",
        "diamond_configurations": "[{\"diamond_weight\":\"0.05\",\"diamond_qty\":\"1\",\"record_id\":\"0\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"},{\"diamond_weight\":\"0.03\",\"diamond_qty\":\"1\",\"record_id\":\"1\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"}]",
        "product_name": "A Initial Love Diamond Pendant",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "10773",
        "product_data": {
            "metal": [
                {
                    "id": "51429",
                    "name": "Yellow Gold",
                    "sku": "C015406",
                    "code": "yellow-gold",
                    "color": "Yellow",
                    "price": 12544,
                    "cost_price": 12544,
                    "purity": "14K",
                    "purityPrice": 5120,
                    "weight": "2.45",
                    "web_percent": "0.583",
                    "cost_percent": "0.583",
                    "product_metal_id": "51216"
                }
            ],
            "material_detail": "Diamond",
            "stone": [
                {
                    "clarity": "SI GH",
                    "color": "GH",
                    "no_of_diamonds": "1",
                    "weight": "0.05",
                    "shape": "Round",
                    "total_weight": 0.05,
                    "setting_type": "",
                    "price": 6850,
                    "cost_price": 6850,
                    "weight_range": "0.001-0.0749"
                },
                {
                    "clarity": "SI GH",
                    "color": "GH",
                    "no_of_diamonds": "1",
                    "weight": "0.03",
                    "shape": "Round",
                    "total_weight": 0.03,
                    "setting_type": "",
                    "price": 4110,
                    "cost_price": 4110,
                    "weight_range": "0.001-0.0749"
                }
            ],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [
                {
                    "weight": 0.96,
                    "price": 0,
                    "old_price": 0,
                    "code": "beads",
                    "label": "Beads",
                    "is_price_enabled": "0",
                    "is_price_type": "0"
                }
            ],
            "sku": "C015406",
            "making_charge": 6125,
            "making_rate": 2500,
            "price": 28278,
            "discount_applied_price": 35000,
            "discount_label": "20% Off on Stone Price",
            "rating": 4.8,
            "total_rating":50,
            "cost_price": 25849,
            "margin": 15,
            "metal_price": 12544,
            "stone_price": 10960,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 889,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 0,
            "total_metal_weight": 2.45,
            "total_stone_weight": 0.08,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0.96,
            "total_weight": 3.43,
            "total_stone_numbers": 2,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": "17.25 inches",
            "sub_size": "43.82 cm",
            "is_priority_shipping": 1,
            "priorityshipping_id": 302500,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4326123",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C008505_1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "51216"
                },
                {
                    "id": "4326126",
                    "label": "Diagonal View-Left",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C008505_6.jpeg",
                    "sort_order": "11",
                    "roles": "hover",
                    "product_metal_id": "51216"
                },
                {
                    "id": "4326129",
                    "label": "Front Full View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C008505_Creative.jpeg",
                    "sort_order": "12",
                    "roles": "",
                    "product_metal_id": "51216"
                },
                {
                    "id": "4326132",
                    "label": "Dimension Image View",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C008505_2.jpeg",
                    "sort_order": "13",
                    "roles": "",
                    "product_metal_id": "51216"
                },
                {
                    "id": "4326135",
                    "label": "Front View-Open Lock",
                    "metal_image": "https://www.candere.com/media/jewellery/images/C008505_3.jpeg",
                    "sort_order": "14",
                    "roles": "",
                    "product_metal_id": "51216"
                }
            ],
            "videos": []
        }
    },
    {
        "priorityshipping_id": "191140",
        "product_type": "584",
        "parent_product_sku": "C022008",
        "metal_selection": "105580,105535",
        "metal_karat_selection": "14k",
        "diamond_quality": "139015",
        "product_size": "",
        "chain_thickness": "",
        "gold_metal_weight": "3.17",
        "silver_metal_weight": "0.00",
        "platinum_metal_weight": "0.00",
        "weight": "3.21",
        "priority_order": "1",
        "qty": "1",
        "is_active": "1",
        "order_id": "401100024167",
        "order_item_id": "401100024167",
        "store": "",
        "offline_store_identifier": "MH002",
        "created_at": "2024-10-28 06:18:30",
        "updated_at": "2025-03-26 12:07:47",
        "design_identifier": "cner2814",
        "is_48_hours_available": null,
        "pin_codes": null,
        "product_barcode": "401100024167",
        "diamond_configurations": "[{\"diamond_weight\":\"0.03\",\"diamond_qty\":\"2\",\"record_id\":\"0\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"},{\"diamond_weight\":\"0.00625\",\"diamond_qty\":\"16\",\"record_id\":\"1\",\"initialize\":\"true\",\"diamond_shape\":\"Round\",\"diamond_setting_type\":\"\"}]",
        "product_name": "Glen Platinum Bracelet",
        "is_frontend_active": "1",
        "is_active_video_call": null,
        "selling_price": null,
        "price_info": null,
        "product_id": "35380",
        "product_data": {
            "metal": [
                {
                    "id": "105535",
                    "name": "Rose Gold",
                    "sku": "C022008",
                    "code": "rose-gold",
                    "color": "Rose",
                    "price": 16230,
                    "cost_price": 16230,
                    "purity": "14K",
                    "purityPrice": 5120,
                    "weight": "3.17",
                    "web_percent": "0.583",
                    "cost_percent": "0.583",
                    "product_metal_id": "105580"
                }
            ],
            "material_detail": "Diamond",
            "stone": [
                {
                    "clarity": "SI IJ",
                    "color": "IJ",
                    "no_of_diamonds": "2",
                    "weight": "0.03",
                    "shape": "Round",
                    "total_weight": 0.06,
                    "setting_type": "",
                    "price": 7140,
                    "cost_price": 14280,
                    "weight_range": "0.001-0.0749"
                },
                {
                    "clarity": "SI IJ",
                    "color": "IJ",
                    "no_of_diamonds": "16",
                    "weight": "0.00625",
                    "shape": "Round",
                    "total_weight": 0.1,
                    "setting_type": "",
                    "price": 11900,
                    "cost_price": 190400,
                    "weight_range": "0.001-0.0749"
                }
            ],
            "gemstone": [],
            "zirconia": [],
            "othermaterial": [],
            "sku": "C022008",
            "making_charge": 7925,
            "making_rate": 2500,
            "price": 138527,
             "discount_applied_price": 174556,
            "discount_label": "20% Off on Stone Price",
            "rating": 5,
            "total_rating":10,
            "cost_price": 229660,
            "margin": 2,
            "metal_price": 16230,
            "stone_price": 19040,
            "gemstone_price": 0,
            "gst_percentage": "3",
            "gst": 1296,
            "zirconia_price": 0,
            "othermaterial_price": 0,
            "old_price": 0,
            "total_metal_weight": 3.17,
            "total_stone_weight": 0.16,
            "total_gemstone_weight": 0,
            "total_zirconia_weight": 0,
            "total_othermaterial_weight": 0,
            "total_weight": 3.2,
            "total_stone_numbers": 18,
            "total_gemstone_numbers": 0,
            "total_zirconia_numbers": 0,
            "othermaterial_is_price_enabled": 0,
            "size": null,
            "sub_size": "",
            "is_priority_shipping": 1,
            "priorityshipping_id": 191140,
            "price_breakup_limit": 15000,
            "enable_price_breakup": "1",
            "dgrp_limit": 10000,
            "images": [
                {
                    "id": "4719061",
                    "label": "Front Image view",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC06397PLTYG_1_1.jpeg",
                    "sort_order": "10",
                    "roles": "base,small,thumbnail",
                    "product_metal_id": "105580"
                },
                {
                    "id": "4719064",
                    "label": "Diagonal View-Left",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC06397PLTYG_2_1.jpeg",
                    "sort_order": "11",
                    "roles": "hover",
                    "product_metal_id": "105580"
                },
                {
                    "id": "4719067",
                    "label": "Side View 1",
                    "metal_image": "https://www.candere.com/media/jewellery/images/KC06397PLTYG_3.jpeg",
                    "sort_order": "12",
                    "roles": "",
                    "product_metal_id": "105580"
                }
            ],
            "videos": []
        }
    },
   
]
export default products